apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
data:
  policy.default: role:readonly
  scopes: '[email, groups]'
  # policy.default: ""
  policy.csv: |
    g, hugo@*****.co.kr, role:admin
    g, philip@*****.co.kr, role:admin
    g, roy@*****.co.kr, role:admin
    g, jaden.youn@*****.co.kr, role:admin
    g, leo@*****.co.kr, role:admin
    g, derek@*****.co.kr, role:admin
    g, evan@*****.co.kr, role:admin
    g, ryan@*****.co.kr, role:readonly
    g, hugo-test@*****.co.kr, role:readonly
