{{- range .Values.repositories }}
apiVersion: v1
kind: Secret
metadata:
  name: repo-{{ .name }}
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
  annotations:
    argocd.argoproj.io/sync-wave: "1" # 가장 먼저 실행
stringData:
  type: git
  url: {{ .url | quote }}
  sshPrivateKey: {{ .sshPrivateKey | quote }}
---
{{- end }}