{{- range .Values.projects }}
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .name }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2" # 레포 등록 후 실행
spec:
  description: {{ .description | quote }}
  sourceRepos:
    {{- range .sourceRepos }}
    - {{ . | quote }}
    {{- end }}
  destinations:
    {{- range .destinations }}
    - server: {{ .server | quote }}
      namespace: {{ .namespace | quote }}
    {{- end }}
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
---
{{- end }}