

# # ACM 인증서 연결 (ACM에서 발급받은 ARN 넣기)  N 개 일때 , 로 연결  예시-arn:1, arn:2
# arn: arn:aws:acm:ap-northeast-2:365485194891:certificate/e885ba4f-8d7c-43f0-9923-d053338fc8b8

# # main ALB ALB 1개로 사용하기 위함.
groupName : prod-mgmt-hub


# 생성할 인그레스 목록
ingresses:
  - name: "main-alb"    # 인그레스 이름 (예: alb-base-provisioner-ingress 로 생성됨)
    namespaceApp: "infra-system"    # 인프라 자원이므로 infra-system 등에 배포