apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.serviceAccountName }}-token
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/service-account.name: {{ .Values.serviceAccountName | quote }}
type: kubernetes.io/service-account-token