apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-<<CLUSTER>>-root-apps   # 예: dev-cms-root-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@bitbucket.org:*******/mgmt-hub-cluster.git
    targetRevision: main
    path: argocd/clusters/<<CLUSTER>>/apps   # 예: argocd/clusters/cms/apps
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
