apiVersion: v1
kind: Service
metadata:
  name: {{ include "test-app.fullname" . }}-service
  namespace: {{ .Release.namespace }}
  labels:
    {{- include "test-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP        # 내부에서만 사용 (Ingress 통해 외부 노출 예정)
  selector:
    app: {{ include "test-app.name" . }}
  ports:
    - name: http
      port: 80           # 클러스터 내부에서 서비스가 노출할 포트
      targetPort: 80     # pod 내부의 컨테이너 포트

