apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  url: https://{{ .Values.ingress.host }}
  dex.config: |
    connectors:
    - type: google
      id: google
      name: Google
      config:
        clientID: {{ .Values.google.clientID }}
        clientSecret: {{ .Values.google.clientSecret }}
        hostedDomains:
          - {{ .Values.google.hostedDomain }}
