{{- range .Values.apps }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: argocd
  {{- if $.Values.cascadeDelete }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  {{- end }}
spec:
  destination:
    namespace: {{ .namespace }}
    server: {{ $.Values.spec.destination.server }}
  project: default
  source:
    path: {{ .path }}
    repoURL: {{ $.Values.repoURL }}
    targetRevision: {{ $.Values.targetRevision }}
    helm:
      valueFiles:
        {{- range .valueFiles }}
        - {{ . }}
        {{- end }}
  {{- with $.Values.syncPolicy }}
  syncPolicy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- end }}
