apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-signage-root-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@bitbucket.org:*******/mgmt-hub-cluster.git
    targetRevision: main
    path: argocd/clusters/signage/apps
    helm:
      valueFiles:
        - values.yaml
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
